### ISSUE TITLE
Update composer instructions on Getting Started wiki page

### ISSUE THREAD

**Issue by lcabrini** [lcabrini/sokms#10]
I realized that composer update will actually try to fetch the latest version of all the vendor files and upgrades the composer.lock file. This is maybe not a good idea for two reasons:

1. We might get quite a few merge requests because of this (we just had one)
2. We should be careful about upgrading the vendor files. (this should be tightly controlled as it could cause breakage).

I think there is a composer install that will rather install the versions of all packages that are mentioned in composer.lock. That is, it will not modify composer.lock. But am not entirely sure. Can we look into this and update the wiki page to use **composer install** instead of **composer update**, if this should be the case?

**Comment by lcabrini** [comment]
I just confirmed that this seems to be the case: composer install just installs without updating composer.lock.

**Comment by lcabrini** [comment]
I'll do the wiki updates

**Comment by lcabrini** [comment]
I have made the change. Can you please review and if it is OK we can close.

**Comment by Prince-linux** [comment]
can't see the wiki 
can you please update me with a link ..

**Comment by lcabrini** [comment]
https://github.com/lcabrini/sokms/wiki

**Comment by Prince-linux** [comment]
+1
we can close now
