### ISSUE TITLE
rename class: student -> Student

### ISSUE THREAD

**Issue by lcabrini** [lcabrini/sokms#11]
The laravel convention is to use camel case with first letter capitalized on class names. Let's try to stick to that convention. Two changes need to be done:

1. rename the file to Student.php
2. In the file, rename the class to Student

**Comment by Prince-linux** [comment]
Done please

**Comment by CollinsLord** [comment]
@Prince-linux let me know when you are working on an issue.Thank you

**Comment by lcabrini** [comment]
OK, with more than one committer to the repo it is time to learn on very important new skill: collaboration.  Easy to say, but it takes practice to implement. Now it becomes more crucial to flag that you are wokring on an issue.

Done right, collaboration will allow us to work faster on a project. Done wrong, it will cause the project to stagnate due to infighting and multiple developers working on the same thing.

**Comment by Prince-linux** [comment]
Thank you...

**Comment by Prince-linux** [comment]
I have heard you my bosses... I'll flag or alert you on the issues I am working on always ...

**Comment by lcabrini** [comment]
It wasn't meant for you in particular. What I was trying to say is that to collaborate there are several DOs and DON'Ts:

1. DO notify others when you are working on something
2. DO let others know if you need help on a task you have assigned yourself to
3. DO engage on the issue tracker to help others as much as possilbe
3. DON'T use anger or accusing tone on the issue tracker
4. DON'T make giant commits that make it difficult for everybody

and so on... We are all learning here. So let's all be ready to adapt ourselves a bit (me included).

**Comment by Prince-linux** [comment]
Thank you Maestro

**Comment by CollinsLord** [comment]
Thanks well understood.

**Comment by lcabrini** [comment]
So, can I close this issue now?

**Comment by CollinsLord** [comment]
+1
