### ISSUE TITLE
Add login

### ISSUE THREAD

**Issue by lcabrini** [lcabrini/sokms#2]
User should be required to log in to use the application.

**Comment by lcabrini** [comment]
This may prove useful: https://laravel.com/docs/5.4/authentication

**Comment by lcabrini** [comment]
I have enable basic authentication. I forgot to reference this issue in the commit message.

**Comment by lcabrini** [comment]
Is this issue resolved? I suggest we close it. If there are more things to do related to auth, we can open new tickets for those.

**Comment by CollinsLord** [comment]
+1
