### ISSUE TITLE
Create a getting started document on the wiki

### ISSUE THREAD

**Issue by lcabrini** [lcabrini/sokms#4]
Create a document on how to get set up.

**Comment by lcabrini** [comment]
Draft created here: https://github.com/lcabrini/sokms/wiki

Please review and give feedback.

**Comment by Prince-linux** [comment]
kk

**Comment by Prince-linux** [comment]
assign me too so I can edit the wiki and send the feedback pls

**Comment by lcabrini** [comment]
Ah, no write access on the wiki? Ok, let me see how I can enable...

**Comment by lcabrini** [comment]
I have seen the updates. That looks fine. Is there still anything to be added or can I close this issue?

**Comment by Prince-linux** [comment]
you can close it now that's all
