### ISSUE TITLE
Create student model

### ISSUE THREAD

**Issue by lcabrini** [lcabrini/sokms#5]
We need a model for a student. Here should be a students contact details, including:
* full name
* date of birth
* address
* phone numbers
* email
* github account

**Comment by Prince-linux** [comment]
I am working on this too pls

**Comment by lcabrini** [comment]
Ok, thanks.

**Comment by Prince-linux** [comment]
having issues maestro 
can you pls go through these screenshots and get back to me pls??
![screen shot 2017-07-31 at 5 10 50 pm](https://user-images.githubusercontent.com/12966365/28788846-1b695b36-7612-11e7-824a-d5fbc3521fd6.png)

**Comment by Prince-linux** [comment]
![screen shot 2017-07-31 at 5 10 29 pm](https://user-images.githubusercontent.com/12966365/28788928-75e7596e-7612-11e7-9184-3afd44630b4e.png)

**Comment by lcabrini** [comment]
I think there is no datatype called srting. Try string instead ;)

**Comment by Prince-linux** [comment]
so instead of table->string('full name');
should i do this instead??
table->str('full name'); or table->('full name name');

**Comment by Prince-linux** [comment]
I have seen the error pls

**Comment by Prince-linux** [comment]
It was a name error
instead of string ,, i wrote srting

**Comment by Prince-linux** [comment]
lol

**Comment by lcabrini** [comment]
OK, I have merged. Can we close?

**Comment by lcabrini** [comment]
The student model is there, but it seems empty...

**Comment by lcabrini** [comment]
Sorry, my mistake. I forgot that in Laravel you have to look at the migration files. Setting this to invalid. I suggest we close.

**Comment by Prince-linux** [comment]
+1

**Comment by lcabrini** [comment]
Actually, the original issue was not invalid. It was one of my comments that was invalid. So removed the tag.
