### ISSUE TITLE
Disable user registration

### ISSUE THREAD

**Issue by lcabrini** [lcabrini/sokms#8]
The user registration should not be available. The admin user will be in charge of creating users (if that is even needed).

**Comment by CollinsLord** [comment]
So I can disable right 

_Sent from my TECNO-C9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by lcabrini** [comment]
I have merged this. Can I close?

**Comment by CollinsLord** [comment]
+1
